### ISSUE TITLE
sudachi adds extra indent when creating a task list

### ISSUE THREAD

**Issue by tetsuya** [kato1628/Sudachi#115]
This is how you write a task list using markdown syntax.

```markdown
- [ ] incomplete item
```

When you do this, Sudachi adds extra indent.
![oct-31-2017 11-27-59](https://user-images.githubusercontent.com/1000796/32204780-a216deb0-be2e-11e7-8a70-34d75d68873d.gif)

**Comment by kato1628** [comment]
@tetsuya Thx! I will try to fix this bug in next release :)

**Comment by kato1628** [comment]
ozaki and habu also feedback same issue.

**Comment by kato1628** [comment]
@tetsuya It seems to be fixed this bug. I will release fixed version app in v0.2.1.
