### ISSUE TITLE
[feature request] Add starting time on the timeline

### ISSUE THREAD

**Issue by tetsuya** [kato1628/Sudachi#116]
Would you be able to display the starting time of tasks on timeline?

The calendar app on macOS displays an event like this. I find it much easier to recognize the starting time this way.
![screen shot 2017-10-31 at 12 39 33](https://user-images.githubusercontent.com/1000796/32207361-c70829c6-be3e-11e7-8e2d-e2981b8ea297.png)

This is a capture from Sudachi. This is quite hard to tell whether it is starting from 14:15 or 14:30.

![screen shot 2017-10-31 at 13 32 10](https://user-images.githubusercontent.com/1000796/32207536-f31cab9e-be3f-11e7-8d73-6f86194fe4fb.png)

**Comment by kato1628** [comment]
@tetsuya Thx. It seems like possible. I will look into whether I would be able to display starting time on timetable.

**Comment by kato1628** [comment]
@tetsuya move to https://github.com/sudachiapp/forum/issues/15
