### ISSUE TITLE
task list data is deleted

### ISSUE THREAD

**Issue by kato1628** [kato1628/Sudachi#120]
feedbacked by habu.

**Steps to reproduce**
1. Edit task in a date.
2. Click a date button except the date selected in step 1 from left sidebar.
3. Quit Sudachi.
4. Start Sudachi.
5. Task data of date selected in step 1 will be deleted.

**Comment by kato1628** [comment]
It seems to be fixed. I will Release fixed app in v0.2.1.

**Comment by kato1628** [comment]
This bug still seems to occur in win v0.2.0 app 😞

**Comment by equus52** [comment]
The task list of yesterday was deleted in mac version Sudachi v0.2.1.
I do not clearly understand the reproduction condition.
I will tell you if I find something.

**Comment by kato1628** [comment]
fixed in v0.2.2.
https://github.com/kato1628/Sudachi/releases/tag/v0.2.2
