### ISSUE TITLE
Seems to be typo: "Sing out"

### ISSUE THREAD

**Issue by ytakahashi1981** [kato1628/Sudachi#122]
![image](https://user-images.githubusercontent.com/16332474/32472029-c69ed894-c3a3-11e7-8a4f-0963d7143798.png)

"Sign out"?

**Comment by kelaductor** [comment]
https://github.com/kato1628/Sudachi/pull/124

**Comment by kato1628** [comment]
Thx. I have merged pr #124

**Comment by kato1628** [comment]
fixed in v0.2.2.
https://github.com/kato1628/Sudachi/releases/tag/v0.2.2
