### ISSUE TITLE
The task list is overwritten by the cheat sheet.

### ISSUE THREAD

**Issue by equus52** [kato1628/Sudachi#128]
Reproduction procedure (mac v0.2.1)

1. Edit the task list
2. Open the cheat sheet
3. Quit Sudachi
4. Start Sudachi
5. The task list is deleted and overwritten with the contents of the cheat sheet

**Comment by kato1628** [comment]
@equus52 It will be fixed by commit 91be5584698a54aedc9558e7a652092c8302b953.

**Comment by kato1628** [comment]
fixed in v0.2.2.
https://github.com/kato1628/Sudachi/releases/tag/v0.2.2
