### ISSUE TITLE
The task list is deleted by signing out

### ISSUE THREAD

**Issue by equus52** [kato1628/Sudachi#129]
Reproduction procedure (mac v0.2.1)

1. Edit the task list
2. Sign out
3. Sign in
5. The task list is deleted.

**Comment by kato1628** [comment]
Thank you for pr #130 :)

**Comment by kato1628** [comment]
I will release fixed ver app in v0.2.2

**Comment by kato1628** [comment]
fixed in v0.2.2.
https://github.com/kato1628/Sudachi/releases/tag/v0.2.2
