### ISSUE TITLE
タイムラインのスクロール度合いによってはタスク追加時にタイムラインのフィードバックが見えない

### ISSUE THREAD

**Issue by dai---chi** [kato1628/Sudachi#58]
細かい指摘ですみません 🙇 

- タスクが追加されるデフォルトの時間を現在時刻あたりにした方がよさそう…？
- タイムラインの中で追加されたタスクの場所に自動スクロールしてくれるとハッピーかも

**Comment by kato1628** [comment]
@dai---chi move to https://github.com/sudachiapp/forum/issues/7
